/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings cloudflare-bindings.d.ts` (hash: 4598a7f1be7ab6b6f33fe2f765121464)
interface __BaseEnv_CloudflareBindings {
	DB: D1Database;
	ALLOWED_ORIGIN: string;
	MAX_FILE_SIZE_BYTES: string;
	MAX_ACTIVE_DOWNLOADS: string;
	SUBMISSION_COOLDOWN_SECONDS: string;
	SEEDR_MODE: string;
	SEEDR_ACCESS: string;
	SEEDR_ACCOUNT_CONFIG: string;
	SEEDR_ACCOUNT_A_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGIN" | "MAX_FILE_SIZE_BYTES" | "MAX_ACTIVE_DOWNLOADS" | "SUBMISSION_COOLDOWN_SECONDS" | "SEEDR_MODE" | "SEEDR_ACCESS" | "SEEDR_ACCOUNT_CONFIG" | "SEEDR_ACCOUNT_A_TOKEN">> {}
}
