import {useState} from 'react';
import {Routes,Route,Link,useNavigate} from 'react-router-dom';
import {ArrowLeft,Download,Eye,File,Folder,HardDrive,Info,Link2,MoreVertical,Music,Play,Plus,Settings,Share2,Video} from 'lucide-react';
import {mockFiles} from './mockData';
import type {LinkBoxFile} from './types';

const Icon=({f}:{f:LinkBoxFile})=><span className={'fi '+f.kind}>{f.kind==='folder'?<Folder/>:f.kind==='video'?<Video/>:f.kind==='audio'?<Music/>:<File/>}</span>;
const Brand=()=> <div className="brand"><span className="logo">L</span><b>Link<span>Box</span></b></div>;
function Shell({children,title,back=false}:{children:React.ReactNode,title?:string,back?:boolean}){const n=useNavigate();return <main><header>{back?<button onClick={()=>n(-1)}><ArrowLeft/></button>:<Brand/>}<b>{title}</b><Link to="/settings"><Settings/></Link></header>{children}</main>}
function Row({f}:{f:LinkBoxFile}){const n=useNavigate();const open=()=>n(f.kind==='folder'?'/folder':f.kind==='video'||f.kind==='audio'?'/player':'/preview');return <div className="row" onClick={open}><Icon f={f}/><div className="meta"><b>{f.name}</b><small>{f.size}{f.subtitle?' • '+f.subtitle:''}</small>{f.status==='ready'?<em>● Ready</em>:<><div className="bar"><i style={{width:(f.progress||0)+'%'}}/></div><small>{f.status==='fetching'?'Fetching metadata':'Downloading'} • {f.progress}%</small></>}</div>{f.status==='ready'&&<Download/>}<MoreVertical/></div>}
const Nav=()=> <nav><Link to="/files"><Folder/>Files</Link><Link to="/storage"><HardDrive/>Storage</Link></nav>;
function Home(){const n=useNavigate();const[v,setV]=useState('');return <Shell><section className="hero"><div className="heroLogo">L</div></section><div className="paste"><Link2/><input value={v} onChange={e=>setV(e.target.value)} placeholder="Paste magnet link..."/><button onClick={()=>v.startsWith('magnet:?')&&n('/progress')}><Plus/></button></div><section><div className="title"><b>Recent Files</b><Link to="/files">See all</Link></div>{mockFiles.slice(0,4).map(f=><Row key={f.id} f={f}/>)}</section><Nav/></Shell>}
function Progress(){return <Shell title="Add Link" back><section><div className="card"><Row f={mockFiles[1]}/><div className="steps"><p>✓ Added</p><p>✓ Fetching metadata</p><p className="blue">● Downloading — 58%</p><p>○ Processing</p><p>○ Ready</p></div></div><button className="cancel">Cancel</button></section></Shell>}
function Files(){return <Shell><section><Link className="storage" to="/storage"><HardDrive/><div className="bar"><i style={{width:'65%'}}/></div><b>6.2 / 9.5 GB</b></Link><div className="tabs"><b>All</b><span>Downloading 1</span><span>Ready 4</span></div>{mockFiles.map(f=><Row key={f.id} f={f}/>)}</section><Link className="fab" to="/"><Plus/></Link><Nav/></Shell>}
function FolderPage(){return <Shell title="Project Files" back><section><div className="folderHead"><Folder/><div><b>Project Files</b><small>12 files • 2.8 GB</small></div></div>{mockFiles[1].children?.map(f=><Row key={f.id} f={f}/>)}</section></Shell>}
function Preview(){return <Shell title="User Guide.pdf" back><div className="preview"><article><Brand/><h2>Quick Start Guide</h2><p/><p/><p/><p/></article><span>1 / 12</span></div><div className="actions"><button><Share2/>Share</button><button><Download/>Download</button><button><File/>Open in…</button></div></Shell>}
function Player(){return <Shell title="Sample Video.mkv" back><div className="player"><div className="mountain"><button><Play/></button></div></div><section><Row f={{...mockFiles[0],status:'ready'}}/><button className="primary"><Download/>Download</button></section></Shell>}
function Storage(){return <Shell title="Storage" back><section><div className="bigCard"><HardDrive/><h1>6.2 GB</h1><small>of 9.5 GB used</small><div className="bar"><i style={{width:'65%'}}/></div><div className="available"><b>3.3 GB</b><small>Available</small></div></div><div className="list"><p>Total Storage <b>9.5 GB</b></p><p>Used Storage <b>6.2 GB</b></p><p>Available <b>3.3 GB</b></p></div></section></Shell>}
function Full(){return <Shell back><section className="center"><div className="warn">!</div><h2>Not enough space</h2><p>Your file needs 2.5 GB but only 500 MB is available.</p><div className="card"><Row f={mockFiles[1]}/></div><h4>Files that can be cleared</h4><div className="card"><label>Old Video.mkv <input type="checkbox"/></label><label>Backup Files <input type="checkbox"/></label></div><button className="primary">Free space & continue</button><button className="secondary">Cancel</button></section></Shell>}
function SettingsPage(){return <Shell title="Settings" back><section><div className="card"><b>Appearance</b><label><input type="radio" name="t" defaultChecked/> System</label><label><input type="radio" name="t"/> Light</label><label><input type="radio" name="t"/> Dark</label></div><div className="menu"><Link to="/storage"><HardDrive/>Storage</Link><Link to="/about"><Info/>About LinkBox</Link><Link to="/about"><Info/>How it works</Link><Link to="/about"><File/>Privacy</Link></div><footer><Brand/><small>Version 1.0.0</small></footer></section></Shell>}
function About(){return <Shell title="About LinkBox" back><section><div className="about"><div className="heroLogo">L</div><h1>Link<span>Box</span></h1></div><div className="info"><details><summary>How it works</summary><p>Paste a magnet link and LinkBox temporarily fetches and stores available files.</p></details><details><summary>Temporary storage</summary><p>Files are automatically removed after 24 hours.</p></details><details><summary>Shared storage</summary><p>Files are protected from shared cleanup for 3 hours. Older files may be cleared when space is needed.</p></details><details><summary>File support</summary><p>Video, audio, images, PDF, documents, archives, folders and other downloadable files.</p></details><details><summary>Important</summary><p>LinkBox is temporary storage. Only add content you are authorized to access.</p></details></div></section></Shell>}
function Missing(){return <Shell back><div className="missing"><File/><h2>File unavailable</h2><p>This file is no longer available in LinkBox.</p><Link className="primary" to="/files">Go to files</Link></div></Shell>}
export default function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/progress" element={<Progress/>}/><Route path="/files" element={<Files/>}/><Route path="/folder" element={<FolderPage/>}/><Route path="/preview" element={<Preview/>}/><Route path="/player" element={<Player/>}/><Route path="/storage" element={<Storage/>}/><Route path="/storage-full" element={<Full/>}/><Route path="/settings" element={<SettingsPage/>}/><Route path="/about" element={<About/>}/><Route path="/unavailable" element={<Missing/>}/></Routes>}
